Repository johnthagen/clion-cppcheck, pull requests merged in 2020-11, with the labels that each got.

#43 Fix supported IntelliJ build versions
  README.md
  resources/META-INF/plugin.xml
Labels: bug

#44 Add docs for how to build and run the plugin locally
  README.md
Labels: doc

#45 Document that --enable=unusedFunction is not supported
  README.md
  src/com/github/johnthagen/cppcheck/Configuration.java
  src/com/github/johnthagen/cppcheck/CppcheckInspection.java
  src/com/github/johnthagen/cppcheck/JFilePicker.java
Labels: doc

#46 Show inconclusive annotation in editor
  README.md
  resources/META-INF/plugin.xml
  src/com/github/johnthagen/cppcheck/CppcheckInspection.java
Labels: enhancement

#47 Release 1.5.0
  README.md
  resources/META-INF/plugin.xml
Labels: doc

#50 extracted some code from CppCheckInspection to CppCheckInspectionImpl…
  src/com/github/johnthagen/cppcheck/CppCheckInspectionImpl.java
  src/com/github/johnthagen/cppcheck/CppcheckInspection.java
Labels: refactor
